### ISSUE TITLE
Official host

### ISSUE THREAD

**Issue by totokaka** [XereoNet/SpaceGDN#24]
The server at `gdn.api.xereo.net` does not seem to have been updated in a while.

SpaceGDN needs an official host with capacity to serve all the patched jars from itself. For SpaceGDN to be useful for the patched jars, they need to actually be patched, else they don't work.

The host should have cron configured to upgrade it from this repo, potentionally from a 'stable' branch. cron should also be configured to load new builds(`run.py load`) every x hours.

**Comment by JamyDev** [comment]
And now has https as well + https://gdn.spacecp.net :)

**Comment by JamyDev** [comment]
Going to close this as I feel like having the SpaceCP one is enough for a public version 😉

**Comment by cwysong85** [comment]
Is https://gdn.spacecp.net/v2/ going down anytime soon? Just curious... I may use this as my official endpoint.

**Comment by JamyDev** [comment]
We have no plans of shutting it down, no. Feel free to use it :)
